In [4]:
from kan.KANLayer import KANLayer
import torch

model = KANLayer(in_dim=3, out_dim=5)
x = torch.normal(0,1,size=(1,3))
y, preacts, postacts, postspline = model(x)


In [11]:
x

tensor([[0.6253, 0.4749, 0.5480]])

In [13]:
preacts

tensor([[[0.6253, 0.4749, 0.5480],
         [0.6253, 0.4749, 0.5480],
         [0.6253, 0.4749, 0.5480],
         [0.6253, 0.4749, 0.5480],
         [0.6253, 0.4749, 0.5480]]])

In [15]:
postacts

tensor([[[ 0.0533,  0.2219,  0.1806],
         [-0.2327,  0.0087,  0.0720],
         [-0.0060, -0.1452,  0.1258],
         [-0.0117, -0.0651, -0.0571],
         [-0.1693, -0.0276, -0.0602]]], grad_fn=<PermuteBackward0>)

In [17]:
postspline

tensor([[[-0.0119,  0.0535,  0.0264],
         [-0.0512,  0.0113,  0.0313],
         [ 0.0276, -0.0007,  0.0065],
         [-0.0395, -0.0323, -0.0231],
         [ 0.0012,  0.0277,  0.0027]]], grad_fn=<PermuteBackward0>)

In [19]:
y

tensor([[ 0.4559, -0.1520, -0.0254, -0.1339, -0.2571]], grad_fn=<SumBackward1>)